import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  input: {
    borderRadius: 5,
    paddingVertical: 10,
    paddingLeft: 10,
    backgroundColor: 'rgba(0,0,0,0.05)',
  },
  borderInput: {
    width: '100%',
  },
  textNormal: {
    color: 'rgba(0,0,0,0.7)',
    fontSize: 15,
    fontFamily: 'Kanit-Regular',
  },
  flex: {
    justifyContent: 'center',
    height: '100%',
    alignContent: 'center',
    alignItems: 'center',
  },
  borderInput2: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    position: 'relative',
  },
  borderInputBody: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    margin: 10,
  },
  borderInputBottom: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    margin: 10,
  },
  borderInputTran: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginHorizontal: 5,
    borderTopRightRadius: 70,
    borderTopLeftRadius: 70,
    marginTop: 10,
  },
  borderInput_In: {
    width: '100%',
    flexDirection: 'column',
    justifyContent: 'space-between',
    alignItems: 'center',
    margin: 10,
  },
  circle: {
    width: 50,
    height: 50,
    borderRadius: 300,
    // borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 5,
  },
  borderWhite: {
    flexDirection: 'column',
    height: '100%',
    alignItems: 'center',
    backgroundColor: '#fff',
    borderTopRightRadius: 50,
    borderTopLeftRadius: 50,
  },
  borderTop: {
    backgroundColor: '#fff',
    height: 'auto',
    position: 'absolute',
    width: '90%',
    top: -60,
    borderRadius: 13,
    justifyContent: 'center',
    padding: 10,
    shadowColor: '#000',
    shadowOffset: { width: 1, height: 1 },
    shadowOpacity: 0.4,
    shadowRadius: 3,
    elevation: 5,
    zIndex: 9999,
  },
  bgTitle: {
    backgroundColor: '#2F8DE4',
    paddingRight: 20,
    borderTopRightRadius: 10,
    borderBottomRightRadius: 10,
    paddingVertical: 10,
  },
  borderDetail: {
    backgroundColor: 'rgba(0,0,0,0.2)',
    width: '90%',
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
  },
  textBlue: {
    fontFamily: 'Kanit-Bold',
    color: '#fff',
    fontSize: 16,
    marginLeft: 20,
  },
  buttonUpload: {
    backgroundColor: '#fff',
    paddingVertical: 10,
    paddingHorizontal: 10,
    borderRadius: 5,
    shadowColor: '#000',
    shadowOffset: { width: 1, height: 1 },
    shadowOpacity: 0.4,
    shadowRadius: 3,
    elevation: 5,
    margin: 10,
  },
  buttonCancel: {
    position: 'absolute',
    left: 10,
    top: 60,
    backgroundColor: '#fff',
    paddingVertical: 5,
    paddingHorizontal: 20,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 20,
  },
  buttonSave: {
    position: 'absolute',
    right: 10,
    top: 60,
    backgroundColor: '#fff',
    paddingVertical: 5,
    paddingHorizontal: 20,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 20,
  },
  buttonExit: {
    position: 'absolute',
    left: 10,
    top: 60,
    backgroundColor: '#fff',
    paddingVertical: 5,
    paddingHorizontal: 20,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 20,
  },
  TextCamera: {
    fontFamily: 'Kanit-Regular',
    fontSize: 18,
    padding: 10,
    textAlign: 'center',
  },
  borderCamera: {
    backgroundColor: 'rgba(255,255,255,0.9)',
    width: '80%',
    height: '30%',
    shadowColor: '#000',
    borderRadius: 10,
    shadowOffset: { width: 1, height: 1 },
    shadowOpacity: 0.4,
    shadowRadius: 3,
    elevation: 5,
    position: 'relative',
  },
  FlexCamera: {
    position: 'absolute',
    top: 0,
    left: 0,
    zIndex: 9999,
    justifyContent: 'center',
    alignItems: 'center',
  },
  partCamera: {
    justifyContent: 'space-around',
    alignItems: 'center',
    flex: 1,
    flexDirection: 'row',
  },
  IconClose: {
    position: 'absolute',
    top: 10,
    right: 20,
    color: 'grey',
    zIndex: 9999,
  },
  ButtonCamera: {
    position: 'absolute',
    bottom: 10,
    width: '100%',
    alignItems: 'center',
  },
  ButtonOutside: {
    backgroundColor: 'rgba(255,255,255,0.6)',
    width: 70,
    height: 70,
    borderRadius: 200,
    alignItems: 'center',
    justifyContent: 'center',
  },
  ButtonInside: {
    backgroundColor: 'rgba(255,255,255,1)',
    width: 50,
    height: 50,
    borderRadius: 200,
  },
  deleteImg: {
    marginLeft: 10,
    backgroundColor: 'rgba(255,0,0,0.7)',
    paddingVertical: 10,
    paddingHorizontal: 10,
    borderRadius: 5,
    shadowColor: '#000',
    shadowOffset: { width: 1, height: 1 },
    shadowOpacity: 0.4,
    shadowRadius: 3,
    elevation: 5,
    margin: 10,
  },
  iconFile: {
    backgroundColor: 'rgba(0,0,0,0.4)',
    height: '70%',
    width: 40,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  TextF: {
    fontFamily: 'Kanit-Regular',
    fontSize: 12,
  },
  TextS: {
    fontFamily: 'Kanit-Bold',
    fontSize: 16,
  },
  new_b_doc: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '90%',
    height: 80,
    marginVertical: '1%',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'grey',
    alignItems: 'center',
    padding: 10,
  },
  new_b_text_1: {
    fontFamily: 'Kanit-Bold',
    fontSize: 12,
    color: '#000',
  },
  new_border: {
    width: '100%',
    alignItems: 'center',
  },
  new_icon: {
    flexDirection: 'row',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
});
